
name: Update Summaries

# Controls when the workflow will run
on:
  workflow_dispatch:


jobs:
  # This workflow contains a single job called "build"
  summaries:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bill_summarize    
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          sudo add-apt-repository --yes ppa:alex-p/tesseract-ocr5
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr poppler-utils
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: run pipeline
        env:
          DATABASE_URL: ${{ secrets.DB_CONNECTION_STRING }}
        run: make
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          add: summaries.csv
          message: 'update summary'
        


  
